### ISSUE TITLE
Because of flutter.connect  - it's asking me to install redis

### ISSUE THREAD

**Issue by technotip** [gosquared/flutter#1]
Am using MongoDB for my data storage. When I implement flutter, and try to run node instance, it throws error saying - 

<code><pre>
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to localhost:6379 failed - connect ECONNREF
USED
    at RedisClient.on_error (C:\TF\node_modules\flutter\node
_modules\redis\index.js:189:24)
    at Socket.<anonymous> (C:\TF\node_modules\flutter\node_m
odules\redis\index.js:95:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 8
npm ERR! not ok code 0
</pre></code>

Can someone give me the solution to this..

I just want to get oauthAccessToken and oauthAccessTokenSecret form flutter.

**Comment by angelxmoreno** [comment]
Looking st the source code: https://github.com/gosquared/flutter/blob/master/src/Flutter.js#L97 it looks likt there is currently no way around this. I suggest we add a flag to the options to bypass the creation of a redisClient. something like

```
if (!self.cache && !self.cacheEnabled) {
    self.debug('creating redis client');
    self.cache = redis.createClient(self.opts.redis.port, self.opts.redis.host);
    self.cache.select(self.opts.redis.database);
}
```

I can submit a PR if authors approve.

**Comment by angelxmoreno** [comment]
Besides redis settings being a requirement, it looks like using sessions is also a hard requirement.

**Comment by simontabor** [comment]
fixed this, use

``` js
var flutter = new Flutter({ cache: false });
```
