### ISSUE TITLE
Lib is swallowing Twitter errors

### ISSUE THREAD

**Issue by angelxmoreno** [gosquared/flutter#3]
on https://github.com/gosquared/flutter/blob/master/src/Flutter.js#L33 the error coming from Twitter is lost. Any suggestions on how we can get the lib to return errors coming from Twitter? This would make it easier to debug stuff on the Twitter side. Meanwhile, I'll do some testing.

**Comment by simontabor** [comment]
Yeah it definitely ought to be possible to see/handle those errors.

we could emit an error event, or we could allow an option of an errorHandler (allowing an errorHandler could be pretty handy as you'd be able to send your own error response rather than the plain text one)

**Comment by simontabor** [comment]
hang on, got that wrong.

those functions are user-overridable already, so to handle it yourself simply do the following...

``` js
var flutter = new Flutter({
  connectCallback: function(req, res) {
    if (req.error) {
      // do what you want
      console.log(req.error);
      return res.send('Oh no an error');
    }
  },
  authCallback: function(req, res) {
    if (req.error) {
      // do what you want
      console.log(req.error);
      return res.send('Oh no an error');
    }
    res.redirect(self.opts.completeCallback);
  }
 });
```

**Comment by simontabor** [comment]
Closing this as I think we've got a solution above - reopen if you have any issues :)
